// This file is auto-generated by @hey-api/openapi-ts

import { type Options, sayHelloGet, getAppInfoPost } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { SayHelloGetData, GetAppInfoPostData, GetAppInfoPostError, GetAppInfoPostResponse } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const sayHelloGetQueryKey = (options?: Options<SayHelloGetData>) => createQueryKey('sayHelloGet', options);

export const sayHelloGetOptions = (options?: Options<SayHelloGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await sayHelloGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: sayHelloGetQueryKey(options)
    });
};

export const getAppInfoPostQueryKey = (options: Options<GetAppInfoPostData>) => createQueryKey('getAppInfoPost', options);

export const getAppInfoPostOptions = (options: Options<GetAppInfoPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getAppInfoPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getAppInfoPostQueryKey(options)
    });
};

export const getAppInfoPostMutation = (options?: Partial<Options<GetAppInfoPostData>>): UseMutationOptions<GetAppInfoPostResponse, GetAppInfoPostError, Options<GetAppInfoPostData>> => {
    const mutationOptions: UseMutationOptions<GetAppInfoPostResponse, GetAppInfoPostError, Options<GetAppInfoPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await getAppInfoPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};