// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-next';
import type { SayHelloGetData, SayHelloGetResponse, GetAppInfoPostData, GetAppInfoPostResponse, GetAppInfoPostError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Say Hello
 */
export const sayHelloGet = <ThrowOnError extends boolean = false>(options?: Options<SayHelloGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<SayHelloGetResponse, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * Get App Info
 */
export const getAppInfoPost = <ThrowOnError extends boolean = false>(options: Options<GetAppInfoPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GetAppInfoPostResponse, GetAppInfoPostError, ThrowOnError>({
        url: '/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};