// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type TestDto = {
    name: string;
};

export type TestDto2 = {
    message: string;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type SayHelloGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type SayHelloGetResponses = {
    /**
     * Successful Response
     */
    200: TestDto2;
};

export type SayHelloGetResponse = SayHelloGetResponses[keyof SayHelloGetResponses];

export type GetAppInfoPostData = {
    body: TestDto;
    path?: never;
    query?: never;
    url: '/';
};

export type GetAppInfoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAppInfoPostError = GetAppInfoPostErrors[keyof GetAppInfoPostErrors];

export type GetAppInfoPostResponses = {
    /**
     * Successful Response
     */
    200: TestDto;
};

export type GetAppInfoPostResponse = GetAppInfoPostResponses[keyof GetAppInfoPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};