// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zValidationError = z.object({
    loc: z.array(z.unknown()),
    msg: z.string(),
    type: z.string()
});

export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

export const zTestDto = z.object({
    name: z.string()
});

export const zTestDto2 = z.object({
    message: z.string()
});

export const zSayHelloGetResponse = zTestDto2;

export const zGetAppInfoPostResponse = zTestDto;